version: '3'

services:
  app:
    image: node:22-slim
    container_name: node-app
    tty: true
    restart: always
    volumes:
      - ./node:/usr/src/app
    working_dir: /usr/src/app
    command: node index.js
    networks:
      - challenge
    depends_on:
      db:
        condition: service_healthy
  proxy:
    image: nginx
    container_name: nginx-proxy
    tty: true
    restart: always
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - challenge
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db-mysql
    tty: true
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=challengedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - challenge
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD" ]
      interval: 5s
      timeout: 10s
      retries: 3

networks:
  challenge:
    driver: bridge
